service: todo-app

frameworkVersion: '2'

plugins:
  - serverless-export-env
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      migrate: true
      sharedDb: true
      convertEmptyValues: true
      noStart: true
    migration:
      dir: offline/migrations

  export-env:
    overwrite: true
    enableOffline: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-1
  profile: serverlessadmin
  environment:
    DYNAMODB_TABLE_NAME: ${self:service}-${opt:stage, self:provider.stage}
    TODO_APP_PK: ${self:service}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE_NAME}'

functions:
  create:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: POST
          cors: true

  list:
    handler: todos/list.list
    events:
      - http:
          path: todos
          method: GET
          cors: true

  get:
    handler: todos/get.get
    events:
      - http:
          path: todos/{id}
          method: GET
          cors: true

  update:
    handler: todos/update.update
    events:
      - http:
          path: todos/{id}
          method: PUT
          cors: true

  delete:
    handler: todos/delete.delete
    events:
      - http:
          path: todos/{id}
          method: DELETE
          cors: true

resources:
  Resources:
    TodosDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: content
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: content
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}
