createTodo:
  handler: handlers/index.createTodo
  events:
    - http:
        path: todos
        method: POST
        cors: true
  # role: createTodoRole
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:PutItem
      Resource: ${self:provider.environment.DYNAMODB_ARN}
