deleteTodo:
  handler: handlers/index.deleteTodo
  events:
    - http:
        path: todos/{sk}
        method: DELETE
        cors: true
  # role: deleteTodoRole
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:DeleteItem
      Resource: ${self:provider.environment.DYNAMODB_ARN}
